live_config_reload = true
[window]
    position = { x = 0, y = 0 }
    dimensions = { columns = 100, lines = 30 }
    opacity = 0.7
    blur = true
    title = "Dead"
    decorations = "None"
    decorations_theme_variant = "Dark"
    padding = { x = 5 , y = 5}


[font]
    #normal = { family = "FantasqueSansM Nerd Font Mono 11pt", style = "Regular" }
    builtin_box_drawing = true
    size = 11

[bell]
    animation = "EaseOut"
    duration = 200
    # command = { program = "notify-send", args = ["🔔 Terminal Bell"] }

[mouse]
    hide_when_typing = true

[selection]
    save_to_clipboard = true

[cursor]
    style = {shape = "Beam", blinking = "Off"}

